// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Feed struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    int64
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
